[tool.poetry]
name = "fast-zero"
version = "0.1.0"
description = ""
authors = ["navegantes <raphaelnavegantes@gmail.com>"]
readme = "README.md"
packages = [{ include = "fast_zero" }]

[tool.poetry.dependencies]
python = "3.11.*"
fastapi = "^0.111.0"
pydantic = { extras = ["email"], version = "^2.0.2" }
sqlalchemy = "^2.0.18"
pydantic-settings = "^2.0.1"
alembic = "^1.11.1"
pyjwt = "^2.8.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.9"
psycopg2 = {extras = ["binary"], version = "^2.9.9"}


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-cov = "^5.0.0"
taskipy = "^1.12.2"
ruff = "^0.4.2"
httpx = "^0.27.0"
factory-boy = "^3.3.0"
freezegun = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 79
extend-exclude = ['migrations']
exclude = [".venv"]

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'
indent-style = "space"

[tool.pytest.ini_options]
pythonpath = "."
addopts = '-p no:warnings'

[tool.taskipy.tasks]
lint = 'ruff check --diff && ruff check'
format = 'ruff format && ruff check --fix'
run = 'uvicorn fast_zero.app:app --reload'
pre_test = 'task lint'
test = 'pytest -s -x --cov=fast_zero -vv'
post_test = 'coverage html'
